### PR TITLE
Update filterlist

### PR DESCRIPTION
**Pull request by ICantCodeSMH**
Over 400? Blazse links!! [yay!] (edited with notepad++ and found with viewdns.info and ipinfo.info)

### CODE REVIEW

**Comment by piperun** [comment]
Wow, thanks a lot.
If I had a medal, you would've gotten it with this commit!

**Comment by ICantCodeSMH** [comment]
> 
> 
> Wow, thanks a lot.
> If I had a medal, you would've gotten it with this commit!

I can add like 600 more but I don't know if it would be too much, let me know

**Comment by piperun** [comment]
The more the merrier (as long it's connected to the main point of this filter).

**Comment by ICantCodeSMH** [comment]
> 
> 
> The more the merrier (as long it's connected to the main point of this filter).
I know but some might be false if it's that much as I am using a tool that finds all domains owned under ip grabber domains,but ill try to find all of them and ill make a pull request

**Comment by piperun** [comment]
Well in your case, if it's registered under Blazse's or other 'company' that specializes in IP logging, 
then I think the saying of "if it quacks like a duck, looks like a duck, then it's probably a duck" fits, i.e. block them until it's proven it's used by another non-affiliated & unrelated company both business-wise and industry, since to goal of this filter is to have a zero-tolerance policy towards enabling nefarious IP logging.

**Pull request merged**
