### PR TITLE
Update filterlist

### PR DESCRIPTION
**Pull request by ICantCodeSMH**
added snipe.blue image host ip grabber

### CODE REVIEW

**Comment by piperun** [comment]
Looks good, I'm wondering where is it you can "use" snipe.blue?

**Comment by ICantCodeSMH** [comment]
> 
> 
> Looks good, I'm wondering where is it you can "use" snipe.blue?

Its an ip grabber hosting service made by one person, its not well known but always good to be safe

**Comment by piperun** [comment]
Ah I see, thanks for the pull request!

**Comment by ICantCodeSMH** [comment]
> 
> 
> Ah I see, thanks for the pull request!

Your welcome, i will try find some more grabbers to add to your list

**Pull request merged**
